server:
 port: 8081
 error:
  include-binding-errors: always
  include-message: always
  include-stacktrace: never
  
spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/crm_db
  username: crm_user
  password: 12345
  driver-class-name: org.postgresql.Driver
 jpa:
  hibernate: 
   ddl-auto: update
  show-sql: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  properties:
   '[hibernate.format_sql]': true
 #image
 servlet:
  multipart:
   max-file-size: 2MB
   max-request-size: 2MB   
   
logging:
 file:
  name: log/crm.log
 pattern:
  file: "%d %-5level [%thread] %logger:%msg%n"
 level:
  '[org.springframework.web]' : WARN
  '[org.hibernate]' : INFO
  '[org.visionrent]' : DEBUG
  
management: #actuator
 endpoints:
  web:
   exposure:
    include: '*'
 info:
  env: 
   enabled: true
 endpoint:
  health:
   show-details: always
  shutdown:
   enabled: true 

crm:
 app:
  jwtSecret: crm@!23
  jwtExpirationMs: 8640000000
  # şimdi 100 gün verdik...uzun verelim sonra 1 günlüğe çekebiliriz    iki sıfır sil
   
info:
 application:
  name: 'Mini-CRM Backend App'
  description: 'This is Mini-CRM Backend Project'
  version: '@project.version@'
   

